In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder , StandardScaler
from sklearn.compose import  ColumnTransformer
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.metrics import recall_score, precision_score, classification_report, roc_auc_score, log_loss
from sklearn.neighbors import KNeighborsClassifier

In [2]:
sonar = pd.read_csv(r"D:\Machine_Learning_CDAC-AI\a] Datasets\Sonar.csv")
sonar.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,Class
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [3]:
le = LabelEncoder()
sonar['Class'] = le.fit_transform(sonar['Class'])
X , y = sonar.drop('Class', axis=1), sonar['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26, stratify= sonar['Class'])

In [4]:
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
# accuracy_score(y_test, y_pred)
y_pred_prob = knn.predict_proba(X_test)
roc_auc_score(y_test, y_pred_prob[:,1])

0.8316430020283976

In [5]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred_prob = knn.predict_proba(X_test)
    scores.append([k, roc_auc_score(y_test, y_pred_prob[:,1])])
df_scores = pd.DataFrame(scores, columns=['Ks', 'score'])
df_scores.sort_values('score', ascending=False)

   Ks     score
1   2  0.892495
2   3  0.881846
3   4  0.869168
4   5  0.845335
5   6  0.831643
6   7  0.809331
0   1  0.808316
7   8  0.790568
8   9  0.785497
9  10  0.761156

## HR Dataset

In [8]:
hr = pd.read_csv(r"D:\Machine_Learning_CDAC-AI\a] Datasets\HR_comma_sep.csv")
hr

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,1,0,support,low
14995,0.37,0.48,2,160,3,0,1,0,support,low
14996,0.37,0.53,2,143,3,0,1,0,support,low
14997,0.11,0.96,6,280,4,0,1,0,support,low
14998,0.37,0.52,2,158,3,0,1,0,support,low

In [9]:
X = hr.drop('left',axis=1)
y=hr['left']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=hr['left'])

In [10]:
from sklearn.compose import make_column_selector

ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")

trans = ColumnTransformer(
    transformers=[("OHE", ohe, make_column_selector(dtype_include=object))], remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")

In [11]:
X_trn_ohe = trans.fit_transform(X_train)
X_tst_ohe = trans.transform(X_test)

In [12]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trn_ohe, y_train)
    y_pred_prob = knn.predict_proba(X_tst_ohe)
    scores.append([k, roc_auc_score(y_test, y_pred_prob[:,1])])
df_scores = pd.DataFrame(scores, columns=['Ks', 'score'])
df_scores.sort_values('score', ascending=False)

   Ks     score
6   7  0.975233
5   6  0.974810
7   8  0.974801
4   5  0.974592
9  10  0.974246
8   9  0.974034
3   4  0.973654
2   3  0.970738
1   2  0.967857
0   1  0.955311

## Image Segmentation Data (MultiClass)

In [18]:
import os
os.chdir(r"D:\Machine_Learning_CDAC-AI\a] Datasets") #fetch the dataset from the folder
img = pd.read_csv("Image_Segmentation.csv")
img

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.000000,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.000000,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.000000,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.000000,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.000000,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,GRASS,36,243,9,0.111111,0.0,1.888889,1.851851,2.000000,0.711110,13.333333,9.888889,12.111111,18.000000,-10.333333,-3.666667,14.000000,18.000000,0.452229,2.368311
205,GRASS,186,218,9,0.000000,0.0,1.166667,0.744444,1.166667,0.655555,13.703704,10.666667,12.666667,17.777779,-9.111111,-3.111111,12.222222,17.777779,0.401347,2.382684
206,GRASS,197,236,9,0.000000,0.0,2.444444,6.829628,3.333333,7.599998,16.074074,13.111111,16.666668,18.444445,-8.888889,1.777778,7.111111,18.555555,0.292729,2.789800
207,GRASS,208,240,9,0.111111,0.0,1.055556,0.862963,2.444444,5.007407,14.148149,10.888889,13.000000,18.555555,-9.777778,-3.444444,13.222222,18.555555,0.421621,2.392487
208,GRASS,223,185,9,0.000000,0.0,0.500000,0.349603,2.388889,2.080776,12.962963,11.555555,9.777778,17.555555,-4.222222,-9.555555,13.777778,17.555555,0.445418,1.838850

In [19]:
le = LabelEncoder()
img['Class'] = le.fit_transform(img['Class'])

X = img.drop('Class',axis=1)
y=img['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=img['Class'])

In [20]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred_prob = knn.predict_proba(X_test)
    scores.append([k, log_loss(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'LogLoss score'])
df_scores.sort_values('LogLoss score', ascending=True)  # Best one should be the lowest one

   Ks  LogLoss score
5   6       0.971258
6   7       0.981489
7   8       1.016964
8   9       1.049631
9  10       1.084273
4   5       1.506703
2   3       1.996419
3   4       2.015082
1   2       3.036645
0   1       4.004850

### With Standard Scaling

In [21]:
scaler = StandardScaler().set_output(transform="pandas")
# scaler.fit_transform()

In [22]:
scaler.fit(X_train)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)

In [23]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict_proba(X_tst_scl)
    scores.append([k, log_loss(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'LogLoss score'])
df_scores.sort_values('LogLoss score', ascending=True)

   Ks  LogLoss score
7   8       0.352821
8   9       0.381166
9  10       0.399369
5   6       0.815084
6   7       0.856190
2   3       1.257178
3   4       1.301800
4   5       1.322391
1   2       3.465736
0   1       4.004850

### Using MinMax Scaler

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler = MinMaxScaler().set_output(transform="pandas")
scaler

MinMaxScaler()

In [26]:
scaler.fit(X_train)   # min and max of every column get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)
X_trn_scl

,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
94,0.143426,0.280335,0.0,0.0,0.0,0.039216,0.000665,0.093686,0.013995,0.305448,0.300325,0.343888,0.269680,0.732877,0.406125,0.290179,0.343888,0.258916,0.119513
36,0.079681,0.330544,0.0,0.0,0.0,0.026144,0.000166,0.028513,0.002741,0.791118,0.773539,0.851988,0.743570,0.431507,0.657790,0.162946,0.851988,0.179697,0.080272
16,0.087649,0.309623,0.0,0.0,0.0,0.056645,0.003933,0.065173,0.004689,0.125226,0.137987,0.145066,0.091972,0.956621,0.256991,0.321429,0.145066,0.399751,0.212029
91,0.537849,0.142259,0.0,0.0,0.0,0.047930,0.005774,0.075356,0.007432,0.369997,0.351461,0.422680,0.332034,0.593607,0.500666,0.267857,0.422680,0.259367,0.089892
108,0.593625,0.615063,0.0,0.0,0.0,0.084967,0.006107,0.050916,0.002038,0.058869,0.051136,0.081001,0.042868,0.810502,0.251664,0.473214,0.081001,0.503086,0.108880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,0.482072,0.000000,0.0,0.0,0.0,0.039216,0.001163,0.105906,0.024600,1.000000,1.000000,1.000000,1.000000,0.495434,0.383489,0.560268,1.000000,0.092773,0.001724
136,0.884462,0.213389,0.0,0.0,0.0,0.013072,0.001115,0.016293,0.002444,0.044926,0.030032,0.075847,0.026500,0.755708,0.295606,0.453125,0.075847,0.670370,0.089371
85,0.231076,0.456067,0.0,0.0,0.0,0.084967,0.007426,0.052953,0.009105,0.132972,0.077110,0.219440,0.095090,0.374429,0.620506,0.281250,0.219440,0.681266,0.055540
148,0.354582,0.514644,0.0,0.0,0.0,0.015251,0.000069,0.034623,0.000739,0.014717,0.007305,0.030928,0.004677,0.831050,0.207723,0.526786,0.030928,0.881481,0.095963
61,0.175299,0.326360,0.0,0.0,0.0,0.030501,0.001274,0.028513,0.002308,0.016008,0.000812,0.042710,0.002338,0.764840,0.264980,0.495536,0.042710,0.986111,0.075436

In [27]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict_proba(X_tst_scl)
    scores.append([k, log_loss(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'LogLoss score'])
df_scores.sort_values('LogLoss score', ascending=True)

   Ks  LogLoss score
2   3       0.165250
3   4       0.197000
4   5       0.256929
5   6       0.281758
6   7       0.304352
7   8       0.343368
8   9       0.385612
9  10       0.400394
1   2       2.332495
0   1       2.860607