In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import  ColumnTransformer
from sklearn.metrics import r2_score, log_loss, accuracy_score, roc_auc_score

from sklearn.svm import SVC

from tqdm import tqdm  # Provides the progress of model running
import os

# Linear Kernel (C)

## Sonar Dataset

In [9]:
sonar = pd.read_csv(r"D:\Machine_Learning_CDAC-AI\a] Datasets\Sonar.csv")
le = LabelEncoder()
sonar['Class'] = le.fit_transform(sonar['Class'])
X , y = sonar.drop('Class', axis=1), sonar['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26, stratify= sonar['Class'])

In [10]:
svm=SVC(kernel='linear')  # By_default C = 1
svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)
accuracy_score(y_test, y_pred)

0.8412698412698413

In [11]:
Cs=np.linspace(0.001,1,20)
scores=[]
for c in Cs:
    svm=SVC(kernel='linear', C=c)
    svm.fit(X_train, y_train)
    
    y_pred = svm.predict(X_test)
    
    scores.append([c, accuracy_score(y_test, y_pred)])
    
df_scores = pd.DataFrame(scores, columns=['C', 'Accuracy Score' ])
df_scores.sort_values(['Accuracy Score'], ascending=False).head()

           C  Accuracy Score
19  1.000000         0.84127
18  0.947421         0.84127
17  0.894842         0.84127
16  0.842263         0.84127
15  0.789684         0.84127

In [12]:
# svm=SVC(kernel='linear')  # By_default C = 1
# svm.fit(X_train, y_train)

# y_pred_prob = svm.predict_proba(X_test)
# accuracy_score(y_test, y_pred)          # Error- This 'SVC' has no attribute 'predict_proba' bcz by_default "probability = False" in SVC

svm=SVC(kernel='linear',probability=True, random_state=26)  # set "probability" and "Random_state"
svm.fit(X_train, y_train)

y_pred_prob = svm.predict_proba(X_test)
log_loss(y_test, y_pred_prob)

0.49100661645035415

In [13]:
Cs=np.linspace(0.001,5,20)
scores=[]
for c in Cs:
    svm=SVC(kernel='linear', C=c, probability=True, random_state=26)
    svm.fit(X_train, y_train)
    
    y_pred_prob = svm.predict_proba(X_test)
    
    scores.append([c, log_loss(y_test, y_pred_prob)])
    
df_scores = pd.DataFrame(scores, columns=['C', 'log_loss' ])
df_scores.sort_values(['log_loss'], ascending=True).head()

          C  log_loss
3  0.790316  0.488054
4  1.053421  0.493004
8  2.105842  0.495309
7  1.842737  0.495447
6  1.579632  0.496055

# Polynomial Kernel (C, Degree)

In [14]:
svm=SVC(kernel='poly')  # By_default "C = 1" and "Degree=3" 
svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)
accuracy_score(y_test, y_pred)

0.8571428571428571

In [15]:
Cs=np.linspace(0.001,5,20)
Ds=[2,3,4]
scores=[]

for c in Cs:
    for d in Ds:
        svm=SVC(kernel='poly', probability=True, random_state=26, C=c, degree=d)
        svm.fit(X_train, y_train)
        
        y_pred_prob = svm.predict_proba(X_test)
        
        scores.append([c, d, log_loss(y_test, y_pred_prob)])
    
df_scores = pd.DataFrame(scores, columns=['C', 'Degree', 'Log_Loss' ])
df_scores.sort_values(['Log_Loss'], ascending=True).head()

           C  Degree  Log_Loss
59  5.000000       4  0.390880
56  4.736895       4  0.390901
53  4.473789       4  0.391032
50  4.210684       4  0.391403
41  3.421368       4  0.391449

# RBF Kernel (C, Gamma)

In [16]:
Cs=np.linspace(0.001,5,20)
Gs=np.linspace(0.001,5,20)
scores=[]

for c in Cs:
    for g in Gs:
        svm=SVC(kernel='rbf', probability=True, random_state=26, C=c, gamma=g)
        svm.fit(X_train, y_train)
        
        y_pred_prob = svm.predict_proba(X_test)
        
        scores.append([c, g, log_loss(y_test, y_pred_prob)])
    
df_scores = pd.DataFrame(scores, columns=['C', 'Gamma', 'Log_Loss' ])
df_scores.sort_values(['Log_Loss'], ascending=True).head()

            C     Gamma  Log_Loss
286  3.684474  1.579632  0.231548
306  3.947579  1.579632  0.231668
326  4.210684  1.579632  0.231739
266  3.421368  1.579632  0.231763
346  4.473789  1.579632  0.231820

# Sigmoid Kernel ()

In [18]:
Cs=np.linspace(0.001,5,20)
coef=np.linspace(-5,5,20)
scores=[]

for c in Cs:
    for cf in coef:
        svm=SVC(kernel='sigmoid', probability=True, random_state=26, C=c, coef0=cf)
        svm.fit(X_train, y_train)
        
        y_pred_prob = svm.predict_proba(X_test)
        
        scores.append([c, cf, log_loss(y_test, y_pred_prob)])
    
df_scores = pd.DataFrame(scores, columns=['C', 'COEF0', 'Log_Loss' ])
df_scores.sort_values(['Log_Loss'], ascending=True).head()

            C     COEF0  Log_Loss
384  5.000000 -2.894737  0.420820
364  4.736895 -2.894737  0.421167
344  4.473789 -2.894737  0.422775
304  3.947579 -2.894737  0.422984
284  3.684474 -2.894737  0.423297