In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import classification_report, roc_auc_score, log_loss
from sklearn.metrics import f1_score, accuracy_score, recall_score
from tqdm import tqdm 
from sklearn.naive_bayes import GaussianNB

import os
os.chdir(r"D:\Machine_Learning_CDAC-AI\a] Datasets") 

import warnings
warnings.filterwarnings("ignore")

In [3]:
sonar = pd.read_csv("Sonar.csv")
sonar.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,Class
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [4]:
le = LabelEncoder()
sonar['Class'] = le.fit_transform(sonar['Class'])
X , y = sonar.drop('Class' , axis = 1) , sonar['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=y)

In [5]:
nb = GaussianNB()
nb.fit(X_train,y_train) # Calculates all the apriori probablitites (Test)
y_pred_prob = nb.predict_proba(X_test) # Calculates posterior probabilites (Validation)
print("ROC AUC =", roc_auc_score(y_test, y_pred_prob[:,1]))
y_pred = nb.predict(X_test)
print("Accuracy Score=", accuracy_score(y_test, y_pred))

ROC AUC = 0.8123732251521298
Accuracy Score= 0.6349206349206349

## Glass Identification Dataset

In [7]:
glass = pd.read_csv('Glass.csv')
glass.head(5)

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.0,0.0,building_windows_float_processed
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.0,0.0,building_windows_float_processed
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.0,0.0,building_windows_float_processed
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.0,0.0,building_windows_float_processed
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.0,0.0,building_windows_float_processed

In [8]:
le = LabelEncoder()
glass['Type'] = le.fit_transform(glass['Type'])
X , y = glass.drop('Type' , axis = 1) , glass['Type']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=y)

In [9]:
nb = GaussianNB()
nb.fit(X_train,y_train) # Calculates all the apriori probablitites (Test)
y_pred_prob = nb.predict_proba(X_test) # Calculates posterior probabilites (Validation)
print("Log Loss =", log_loss(y_test, y_pred_prob)) # Because of "multiclass error" we can't use ROC_auc_accuracy.
y_pred = nb.predict(X_test)
print("Accuracy Score=", accuracy_score(y_test, y_pred))

Log Loss = 5.325734873826645
Accuracy Score= 0.36923076923076925

## Image Segmentation Dataset

In [11]:
image = pd.read_csv('Image_Segmentation.csv')
image.head(5)

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.0,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.0,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.0,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.0,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.0,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811

In [12]:
le = LabelEncoder()
image['Class'] = le.fit_transform(image['Class'])
X , y = image.drop('Class' , axis = 1) , image['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=y)

In [13]:
nb = GaussianNB()
nb.fit(X_train,y_train) # Calculates all the apriori probablitites (Test)
y_pred_prob = nb.predict_proba(X_test) # Calculates posterior probabilites (Validation)
print("Log Loss =", log_loss(y_test, y_pred_prob)) # Because of "multiclass error" we can't use ROC_auc_accuracy.
y_pred = nb.predict(X_test)
print("Accuracy Score=", accuracy_score(y_test, y_pred))

Log Loss = 4.442733214582463
Accuracy Score= 0.7619047619047619