In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
import os

## Pizza Sales Dataset

In [22]:
pizza = pd.read_csv(r"D:\Machine_Learning_CDAC-AI\a] Datasets\pizza_sales.csv")
pizza.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1.0,1.0,hawaiian_m,1.0,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2.0,2.0,classic_dlx_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3.0,2.0,five_cheese_l,1.0,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4.0,2.0,ital_supr_l,1.0,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5.0,2.0,mexicana_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

In [23]:
X = pizza[['quantity']]  
y = pizza['total_price'] 

lr = LinearRegression()
lr.fit(X, y)
print(lr.coef_, lr.intercept_)

[16.80732728] -0.3156394994662719

## Boston Dataset

In [25]:
boston = pd.read_csv(r"D:\Machine_Learning_CDAC-AI\a] Datasets\Boston.csv")
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [26]:
X = boston.drop('medv',axis=1)
y=boston['medv']

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
print("MAE =",mean_absolute_error(y_test,y_pred))
print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

MAE = 3.1527714303845022
RMSE = 4.504438687188617
R2 = 0.7467569320916589

### Polynomial Class - Pizza Sales Dataset

In [28]:
X = pizza[['quantity']]  # Dataframe
y = pizza['total_price']      # Series

In [29]:
poly = PolynomialFeatures(degree =2, include_bias=False).set_output(transform="pandas") # include_bias=False removes the constant values
X_poly = poly.fit_transform(X)
X_poly.head()

   quantity  quantity^2
0       1.0         1.0
1       1.0         1.0
2       1.0         1.0
3       1.0         1.0
4       1.0         1.0

In [30]:
lr = LinearRegression()
lr.fit(X_poly, y)
lr.coef_ , lr.intercept_
# array([ 2.48006959e+01, -1.30947333e-02]) -> x(promote)= 2.48006959e+01  x^2(promote^2)=-1.30947333e-02]

# sales = 24.8promote - -0.0130promote^2 - 18.274  (Polynomial Equation)

(array([20.53010776, -1.18655439]), np.float64(-2.85360193409403))

# Polynomial Tranform with 2 and 3 Variables

In [33]:
insure = pd.read_csv(r"D:\Machine_Learning_CDAC-AI\a] Datasets\AutoInsurance.csv")
insure

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,1,2,3.000000,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22.000000,23,24
1,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
2,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
3,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
4,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9130,LA72316,California,23405.987980,No,Basic,Bachelor,10-02-2011,Employed,M,71941,...,89,0,2,Personal Auto,Personal L1,Offer2,Web,198.234764,Four-Door Car,Medsize
9131,PK87824,California,3096.511217,Yes,Extended,College,12-02-2011,Employed,F,21604,...,28,0,1,Corporate Auto,Corporate L3,Offer1,Branch,379.200000,Four-Door Car,Medsize
9132,TD14365,California,8163.890428,No,Extended,Bachelor,06-02-2011,Unemployed,M,0,...,37,3,2,Corporate Auto,Corporate L2,Offer1,Branch,790.784983,Four-Door Car,Medsize
9133,UP19263,California,7524.442436,No,Extended,College,03-02-2011,Employed,M,21941,...,3,0,3,Personal Auto,Personal L2,Offer3,Branch,691.200000,Four-Door Car,Large
9134,Y167826,California,2611.836866,No,Extended,College,2/14/11,Unemployed,M,0,...,90,0,1,Corporate Auto,Corporate L3,Offer4,Call Center,369.600000,Two-Door Car,Medsize

In [34]:
X = insure[["Income", "Total Claim Amount"]] 
y = insure["Customer Lifetime Value"]
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

,Income,Total Claim Amount,Income^2,Income Total Claim Amount,Total Claim Amount^2
0,10.0,22.000000,1.000000e+02,2.200000e+02,4.840000e+02
1,56274.0,384.811147,3.166763e+09,2.165486e+07,1.480796e+05
2,0.0,1131.464935,0.000000e+00,0.000000e+00,1.280213e+06
3,48767.0,566.472247,2.378220e+09,2.762515e+07,3.208908e+05
4,0.0,529.881344,0.000000e+00,0.000000e+00,2.807742e+05
...,...,...,...,...,...
9130,71941.0,198.234764,5.175507e+09,1.426121e+07,3.929702e+04
9131,21604.0,379.200000,4.667328e+08,8.192237e+06,1.437926e+05
9132,0.0,790.784983,0.000000e+00,0.000000e+00,6.253409e+05
9133,21941.0,691.200000,4.814075e+08,1.516562e+07,4.777574e+05
9134,0.0,369.600000,0.000000e+00,0.000000e+00,1.366042e+05

In [35]:
poly = PolynomialFeatures(degree =3, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

,Income,Total Claim Amount,Income^2,Income Total Claim Amount,Total Claim Amount^2,Income^3,Income^2 Total Claim Amount,Income Total Claim Amount^2,Total Claim Amount^3
0,10.0,22.000000,1.000000e+02,2.200000e+02,4.840000e+02,1.000000e+03,2.200000e+03,4.840000e+03,1.064800e+04
1,56274.0,384.811147,3.166763e+09,2.165486e+07,1.480796e+05,1.782064e+14,1.218606e+12,8.333032e+09,5.698269e+07
2,0.0,1131.464935,0.000000e+00,0.000000e+00,1.280213e+06,0.000000e+00,0.000000e+00,0.000000e+00,1.448516e+09
3,48767.0,566.472247,2.378220e+09,2.762515e+07,3.208908e+05,1.159787e+14,1.347196e+12,1.564888e+10,1.817757e+08
4,0.0,529.881344,0.000000e+00,0.000000e+00,2.807742e+05,0.000000e+00,0.000000e+00,0.000000e+00,1.487770e+08
...,...,...,...,...,...,...,...,...,...
9130,71941.0,198.234764,5.175507e+09,1.426121e+07,3.929702e+04,3.723312e+14,1.025966e+12,2.827067e+09,7.790036e+06
9131,21604.0,379.200000,4.667328e+08,8.192237e+06,1.437926e+05,1.008330e+13,1.769851e+11,3.106496e+09,5.452617e+07
9132,0.0,790.784983,0.000000e+00,0.000000e+00,6.253409e+05,0.000000e+00,0.000000e+00,0.000000e+00,4.945102e+08
9133,21941.0,691.200000,4.814075e+08,1.516562e+07,4.777574e+05,1.056256e+13,3.327489e+11,1.048248e+10,3.302259e+08
9134,0.0,369.600000,0.000000e+00,0.000000e+00,1.366042e+05,0.000000e+00,0.000000e+00,0.000000e+00,5.048890e+07

## Boston Dataset

In [36]:
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [37]:
X = boston.drop('medv',axis=1)
y=boston['medv']

In [38]:
poly = PolynomialFeatures(degree =2, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,...,tax^2,tax ptratio,tax black,tax lstat,ptratio^2,ptratio black,ptratio lstat,black^2,black lstat,lstat^2
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,...,87616.0,4528.8,117482.40,1474.08,234.09,6072.570,76.194,157529.6100,1976.5620,24.8004
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,...,58564.0,4307.6,96049.80,2211.88,316.84,7064.820,162.692,157529.6100,3627.6660,83.5396
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,...,58564.0,4307.6,95064.86,975.26,316.84,6992.374,71.734,154315.4089,1583.1049,16.2409
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,...,49284.0,4151.4,87607.86,652.68,349.69,7379.581,54.978,155732.8369,1160.2122,8.6436
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,...,49284.0,4151.4,88111.80,1183.26,349.69,7422.030,99.671,157529.6100,2115.4770,28.4089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,...,74529.0,5733.0,107013.27,2639.91,441.00,8231.790,203.070,153656.1601,3790.5433,93.5089
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,...,74529.0,5733.0,108353.70,2478.84,441.00,8334.900,190.680,157529.6100,3603.8520,82.4464
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,...,74529.0,5733.0,108353.70,1539.72,441.00,8334.900,118.440,157529.6100,2238.5160,31.8096
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,...,74529.0,5733.0,107411.85,1769.04,441.00,8262.450,136.080,154802.9025,2549.5560,41.9904
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,...,74529.0,5733.0,108353.70,2151.24,441.00,8334.900,165.480,157529.6100,3127.5720,62.0944

In [39]:
X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.6657958510458925

In [40]:
# for degree 3

poly = PolynomialFeatures(degree =3, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = -12709.864328710943

## Housing Dataset

In [42]:
housing = pd.read_csv(r"D:\Machine_Learning_CDAC-AI\a] Datasets\Housing.csv")
housing

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [43]:
dum_hous = pd.get_dummies(housing, dtype=int, drop_first=True)  # drop_first=True drops the one col as two cols created for yes and no
dum_hous

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,2,1,0,1,0,0,0,0,1
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1,0
542,1750000,3620,2,1,1,0,1,0,0,0,0,0,0,1
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,0,1,0,0,0,0,0,0,1

In [44]:
X, y = dum_hous.drop('price', axis=1), dum_hous['price']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=26)

# Simple Linear regression (degree 1)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.6467274812168482

In [45]:
# for degree 2
poly = PolynomialFeatures(degree =2, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.1554227612779322

In [46]:
# for degree 3
poly = PolynomialFeatures(degree =3, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = -2.3890212254733934

## Cases Folder - Concrete Dataset

In [50]:
conc_data = pd.read_csv(r"D:\Machine_Learning_CDAC-AI\a] Datasets\Concrete_Data.csv")
conc_data

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [51]:
X, y = conc_data.drop('Strength', axis=1), conc_data['Strength']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=26)

# Simple Linear regression (degree 1)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.6181464728464399

In [52]:
# for degree 2

poly = PolynomialFeatures(degree =2, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.8116988468481918

In [53]:
# for degree 3

poly = PolynomialFeatures(degree =3, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.7840101067554346

In [54]:
# for degree 4

poly = PolynomialFeatures(degree =4, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = -12.826307333608863

With degree 2 we get best performance