In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import  ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, Ridge
import os
os.chdir(r"D:\Machine_Learning_CDAC-AI\a] Datasets")

In [2]:
housing = pd.read_csv("Housing.csv")
housing

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [3]:
X = housing.drop('price',axis=1)
y=housing['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [4]:
from sklearn.compose import make_column_selector
ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
ohe.fit_transform(housing)
scalar=StandardScaler()
trans = ColumnTransformer(
    transformers=[("OHE", ohe,make_column_selector(dtype_include=object))],remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")
trans.fit_transform(housing)

,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished,price,area,bedrooms,bathrooms,stories,parking
0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,13300000,7420,4,2,3,2
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,12250000,8960,4,4,4,3
2,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,12250000,9960,3,2,2,2
3,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,12215000,7500,4,2,2,3
4,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,11410000,7420,4,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1820000,3000,2,1,1,2
541,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1767150,2400,3,1,1,0
542,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1750000,3620,2,1,1,0
543,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1750000,2910,3,1,1,0
544,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1750000,3850,3,1,2,0

In [5]:
X_trn_trans=trans.fit_transform(X_train)
X_tst_trans=trans.transform(X_test)

In [6]:
lr=LinearRegression()
lr.fit(X_trn_trans,y_train)
y_pred =lr.predict(X_tst_trans)
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.646727481216868

In [7]:
ridge = Ridge()
ridge.fit(X_trn_trans, y_train)
y_pred = ridge.predict(X_tst_trans)
print("R2 Score =",r2_score(y_test, y_pred))

R2 Score = 0.6495238248855243

In [8]:
tst = pd.read_csv("tst_Housing.csv")
tst

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,5600,3,1,2,yes,no,yes,no,no,1,no
1,4355,2,1,1,yes,no,no,no,no,0,no
2,3412,3,1,1,yes,no,no,no,no,0,no
3,6666,2,2,2,yes,yes,no,no,no,0,no

In [9]:
bm=LinearRegression()
X_ohe=trans.fit_transform(X)
bm.fit(X_ohe,y)
X_ohe.columns

Index(['mainroad_yes', 'guestroom_yes', 'basement_yes', 'hotwaterheating_yes',
       'airconditioning_yes', 'prefarea_yes',
       'furnishingstatus_semi-furnished', 'furnishingstatus_unfurnished',
       'area', 'bedrooms', 'bathrooms', 'stories', 'parking'],
      dtype='object')